name: Hyperparameter Tuning

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tuning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: titanic-system
          environment-file: build/conda.yaml
          auto-activate-base: false

      - name: Verify Environment
        shell: bash -el {0}
        run: |
          python --version
          pip list
          python -c "from dotenv import load_dotenv; print('dotenv OK')"

      - name: Run Hyperparameter Tuning
        shell: bash -el {0}
        env:
          DAGSHUB_REPO: ${{ secrets.DAGSHUB_REPO }}
          DAGSHUB_USER: ${{ secrets.DAGSHUB_USER }}
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
		  DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_URI: https://dagshub.com/${{ secrets.DAGSHUB_USER }}/${{ secrets.DAGSHUB_REPO }}.mlflow
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USER }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}

        run: |
          python build/tuning.py

      - name: Upload MLflow Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlruns-artifacts
          path: mlruns/